CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch \
--nproc_per_node=2 \
--master_port 12326 \
downstream_phase/run_phase_training.py \
--batch_size 32 \
--epochs 50 \
--save_ckpt_freq 10 \
--model  surgformer_HTA \
--mixup 0.8 \
--cutmix 1.0 \
--smoothing 0.1 \
--lr 5e-4 \
--layer_decay 0.75 \
--warmup_epochs 5 \
--data_path /home/yangshu/cholec80 \
--eval_data_path /home/yangshu/cholec80 \
--nb_classes 7 \
--data_strategy online \
--output_mode key_frame \
--num_frames 16 \
--sampling_rate 4 \
--eval \
--finetune /home/yangshu/Surgformer/results/surgformer_base_Cataract101_0.0005_0.75_online_key_frame_frame16_Fixed_Stride_4/checkpoint-best/mp_rank_00_model_states.pt \
--data_set Cholec80 \
--data_fps 1fps \
--output_dir /home/yangshu/Surgformer/results/ \
--log_dir /home/yangshu/Surgformer/results/ \
--num_workers 10 \
--dist_eval \
--enable_deepspeed \
--no_auto_resume \
--cut_black