CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch \
--nproc_per_node=4 \
--master_port 12326 \
downstream_phase/run_phase_training.py \
--batch_size 2 \
--epochs 50 \
--save_ckpt_freq 10 \
--model  surgformer_HTA_Mamba \
--pretrained_path /home/syangcw/Surgformer/pretrain_params/timesformer_base_patch16_224_K400.pyth \
--mixup 0.8 \
--cutmix 1.0 \
--smoothing 0.1 \
--lr 5e-4 \
--layer_decay 0.75 \
--warmup_epochs 5 \
--data_path /home/syangcw/datasets/cholec80 \
--eval_data_path /home/syangcw/datasets/cholec80 \
--nb_classes 7 \
--data_strategy online \
--output_mode key_frame \
--num_frames 16 \
--sampling_rate 4 \
--data_set Cholec80 \
--data_fps 1fps \
--output_dir /home/syangcw/Surgformer/results/Cholec80/ \
--log_dir /home/syangcw/Surgformer/results/Cholec80/ \
--num_workers 10 \
--dist_eval \
--no_auto_resume \
--cut_black